// Code generated by selo gen --lang csharp. DO NOT EDIT.
//
// Shared mod-11 reducer used by the numeric / alphanumeric check-digit kinds
// (groups A, B, C). It is parameterized by a CheckDigit spec transcribed from
// the verified selo Go library, so every language port applies the identical
// algorithm.

using System;
using System.Text;

namespace Inovacc.Selo
{
    /// <summary>DV reduction rule (mirrors codegen.DVRule).</summary>
    public enum DVRule
    {
        ElevenMinus,
        ModRemainder,
        RightmostDigit,
        SumZero,
    }

    /// <summary>One check-digit (or, for SumZero, one verify pass) specification.</summary>
    public sealed class CheckDigit
    {
        /// <summary>Positional mod-11 weights, in input (left-to-right) order.</summary>
        public int[] Weights { get; init; } = Array.Empty<int>();

        /// <summary>How the weighted sum becomes the check digit / verification result.</summary>
        public DVRule Rule { get; init; }

        /// <summary>Remainder values (of the rule's fold) that collapse to a 0 check digit.</summary>
        public int[] RemainderTo0 { get; init; } = Array.Empty<int>();

        /// <summary>When true the fold is (sum*10)%11 rather than sum%11 (ModRemainder only).</summary>
        public bool MultiplyBy10 { get; init; }

        /// <summary>Computed value that encodes as the character 'X' (RG: 10). 0 = none.</summary>
        public int EncodeXAt { get; init; }

        /// <summary>Computed value that encodes as the character '0' (RG: 11). 0 = none.</summary>
        public int EncodeZeroAt { get; init; }
    }

    /// <summary>Shared mod-11 primitives used by the check-digit kinds.</summary>
    public static class Mod11
    {
        /// <summary>Alphanumeric CNPJ char -&gt; value map ('0'-'9' -&gt; 0-9, 'A'-'Z' -&gt; 17-42).</summary>
        public static int CharValue(char ch)
        {
            if (ch >= '0' && ch <= '9')
            {
                return ch - '0';
            }

            if (ch >= 'A' && ch <= 'Z')
            {
                return ch - 'A' + 17;
            }

            return -1;
        }

        /// <summary>
        /// WeightedSum computes Sum(values[i] * weights[i]). For cycling weights
        /// (CNPJ) pass cycleRightToLeft=true: the listed single cycle (2..9) is
        /// applied from the rightmost base character, repeating.
        /// </summary>
        public static int WeightedSum(int[] values, int[] weights, bool cycleRightToLeft = false)
        {
            var sum = 0;
            if (cycleRightToLeft)
            {
                var j = 0;
                for (var i = values.Length - 1; i >= 0; i--)
                {
                    sum += values[i] * weights[j];
                    j = (j + 1) % weights.Length;
                }

                return sum;
            }

            for (var i = 0; i < weights.Length; i++)
            {
                sum += values[i] * weights[i];
            }

            return sum;
        }

        /// <summary>
        /// ComputeDigit folds a weighted sum into a numeric check value per the rule.
        /// Returns a number 0..11 (10/11 may be encoded as characters by the caller).
        /// </summary>
        public static int ComputeDigit(int sum, CheckDigit cd)
        {
            switch (cd.Rule)
            {
                case DVRule.ElevenMinus:
                    return 11 - (sum % 11);
                case DVRule.ModRemainder:
                {
                    var rest = cd.MultiplyBy10 ? (sum * 10) % 11 : sum % 11;
                    if (Contains(cd.RemainderTo0, rest))
                    {
                        return 0;
                    }

                    // Two folds share this rule: the "raw remainder" family (CPF/RENAVAM via
                    // *10, and voter_id) maps a high remainder (10/11) to 0 and returns the
                    // remainder itself; the "eleven-minus" family (PIS/CNPJ) maps a low
                    // remainder (0/1) to 0 and returns 11-remainder. The RemainderTo0 set
                    // disambiguates: a set containing >=10 selects the raw-remainder fold.
                    var rawRemainderFold = cd.MultiplyBy10 || HasAtLeast10(cd.RemainderTo0);
                    return rawRemainderFold ? rest : 11 - rest;
                }

                case DVRule.RightmostDigit:
                    return (sum % 11) % 10;
                case DVRule.SumZero:
                    return sum % 11; // valid when 0
                default:
                    return -1;
            }
        }

        /// <summary>EncodeDigit renders a computed value as its check character.</summary>
        public static string EncodeDigit(int value, CheckDigit cd)
        {
            if (cd.EncodeXAt != 0 && value == cd.EncodeXAt)
            {
                return "X";
            }

            if (cd.EncodeZeroAt != 0 && value == cd.EncodeZeroAt)
            {
                return "0";
            }

            return value.ToString(System.Globalization.CultureInfo.InvariantCulture);
        }

        /// <summary>OnlyDigits keeps the ASCII digits of s.</summary>
        public static string OnlyDigits(string s)
        {
            var sb = new StringBuilder(s.Length);
            foreach (var ch in s)
            {
                if (ch >= '0' && ch <= '9')
                {
                    sb.Append(ch);
                }
            }

            return sb.ToString();
        }

        /// <summary>AllEqual reports whether every character of s is identical (s non-empty).</summary>
        public static bool AllEqual(string s)
        {
            if (s.Length == 0)
            {
                return false;
            }

            for (var i = 1; i < s.Length; i++)
            {
                if (s[i] != s[0])
                {
                    return false;
                }
            }

            return true;
        }

        /// <summary>DigitsOf converts each character of s to its numeric value (assumes digits).</summary>
        public static int[] DigitsOf(string s)
        {
            var d = new int[s.Length];
            for (var i = 0; i < s.Length; i++)
            {
                d[i] = s[i] - '0';
            }

            return d;
        }

        private static bool Contains(int[] xs, int v)
        {
            foreach (var x in xs)
            {
                if (x == v)
                {
                    return true;
                }
            }

            return false;
        }

        private static bool HasAtLeast10(int[] xs)
        {
            foreach (var x in xs)
            {
                if (x >= 10)
                {
                    return true;
                }
            }

            return false;
        }
    }
}
