package selo

import (
	"errors"
	"fmt"
	"testing"
)

func TestIE_Kind(t *testing.T) {
	e := NewIE()
	if got := e.Kind(); got != KindIE {
		t.Fatalf("Kind() = %q, want %q", got, KindIE)
	}
}

func TestIE_Registered(t *testing.T) {
	d, ok := Get(KindIE)
	if !ok {
		t.Fatal("IE not registered in registry")
	}
	if d.Kind() != KindIE {
		t.Fatalf("registered Kind() = %q, want %q", d.Kind(), KindIE)
	}
}

func TestIE_ImplementedUFs(t *testing.T) {
	e := NewIE()
	ufs := e.ImplementedUFs()
	want := map[UF]bool{UFSP: true}
	if len(ufs) != len(want) {
		t.Fatalf("ImplementedUFs() = %v, want %d UF(s)", ufs, len(want))
	}
	for _, u := range ufs {
		if !want[u] {
			t.Errorf("ImplementedUFs() returned unexpected UF %q", u)
		}
	}
}

// TestIE_AuthoritativeSamples pins externally-sourced SP IE samples so the
// check-digit convention cannot silently regress. Both numbers are
// independently published (NOT generated by this package) and both check digits
// were verified by hand against the SEFAZ-SP / Sintegra algorithm:
//
//   - 110.042.490.114 — SEFAZ-SP / Sintegra worked example. D1: weights
//     1,3,4,5,6,7,8,10 over digits 1..8 -> sum 164; 164 mod 11 = 10 -> 0 (9th
//     digit). D2: weights 3,2,10,9,8,7,6,5,4,3,2 over digits 1..11 -> sum 125;
//     125 mod 11 = 4 (12th digit).
//   - 388.108.598.269 — published valid SP IE example. D1: sum 250; 250 mod 11
//     = 8 (9th digit). D2: sum 295; 295 mod 11 = 9 (12th digit).
//
// NOTE: these are authoritative-documentation / published worked examples, not
// confirmed real-company registrations (real IE numbers are not publicly
// verifiable); they independently exercise the published SP convention. See
// docs/IE-NOTES.md for sources and the remaining-UF roadmap.
func TestIE_AuthoritativeSamples(t *testing.T) {
	e := NewIE()
	samples := []struct {
		value  string
		source string
	}{
		{"110.042.490.114", "SEFAZ-SP / Sintegra worked example"},
		{"388.108.598.269", "published valid SP IE example"},
	}
	for _, s := range samples {
		t.Run(s.value, func(t *testing.T) {
			if !e.Validate(s.value) {
				t.Errorf("Validate(%q) = false, want true (source: %s)", s.value, s.source)
			}
		})
	}
}

func TestIE_ValidateUF(t *testing.T) {
	e := NewIE()
	tests := []struct {
		name    string
		value   string
		uf      UF
		want    bool
		wantErr error
	}{
		{"valid SP formatted", "110.042.490.114", UFSP, true, nil},
		{"valid SP bare", "110042490114", UFSP, true, nil},
		{"valid SP second sample", "388.108.598.269", UFSP, true, nil},
		{"wrong second check digit", "388.108.598.260", UFSP, false, nil},
		{"wrong first check digit", "110.042.490.914", UFSP, false, nil},
		{"wrong length SP", "12345", UFSP, false, ErrInvalidFormat},
		{"unimplemented UF MG", "110042490114", UFMG, false, ErrUFNotImplemented},
		{"unimplemented UF RJ", "110042490114", UFRJ, false, ErrUFNotImplemented},
		{"invalid UF zz", "110042490114", UF("ZZ"), false, ErrUFNotImplemented},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := e.ValidateUF(tt.value, tt.uf)
			if got != tt.want {
				t.Errorf("ValidateUF(%q,%q) = %v, want %v", tt.value, tt.uf, got, tt.want)
			}
			if tt.wantErr == nil {
				if err != nil {
					t.Errorf("ValidateUF(%q,%q) err = %v, want nil", tt.value, tt.uf, err)
				}
				return
			}
			if !errors.Is(err, tt.wantErr) {
				t.Errorf("ValidateUF(%q,%q) err = %v, want errors.Is %v", tt.value, tt.uf, err, tt.wantErr)
			}
		})
	}
}

func TestIE_Validate(t *testing.T) {
	e := NewIE()
	tests := []struct {
		name  string
		value string
		want  bool
	}{
		{"valid SP formatted", "110.042.490.114", true},
		{"valid SP bare", "110042490114", true},
		{"valid SP second", "388.108.598.269", true},
		{"wrong check", "388.108.598.260", false},
		{"too short", "12345", false},
		{"too long", "1100424901140000", false},
		{"garbage", "abcdefghijkl", false},
		{"empty", "", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := e.Validate(tt.value); got != tt.want {
				t.Errorf("Validate(%q) = %v, want %v", tt.value, got, tt.want)
			}
		})
	}
}

func TestIE_Format(t *testing.T) {
	e := NewIE()
	tests := []struct {
		name    string
		in      string
		want    string
		wantErr error
	}{
		{"bare valid SP", "110042490114", "110.042.490.114", nil},
		{"already formatted", "110.042.490.114", "110.042.490.114", nil},
		{"second sample", "388108598269", "388.108.598.269", nil},
		{"invalid check", "388108598260", "", ErrInvalidFormat},
		{"wrong length", "12345", "", ErrInvalidFormat},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := e.Format(tt.in)
			if tt.wantErr != nil {
				if !errors.Is(err, tt.wantErr) {
					t.Fatalf("Format(%q) err = %v, want errors.Is %v", tt.in, err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("Format(%q) unexpected err: %v", tt.in, err)
			}
			if got != tt.want {
				t.Errorf("Format(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestIE_GenerateRoundTrip(t *testing.T) {
	e := NewIE()
	for i := 0; i < 1000; i++ {
		v := e.Generate()
		if v == "" {
			t.Fatal("Generate() returned empty string")
		}
		if !e.Validate(v) {
			t.Fatalf("Generate() produced invalid IE: %q", v)
		}
	}
}

func TestIE_RegistryDispatch(t *testing.T) {
	ok, err := Validate(KindIE, "110.042.490.114")
	if err != nil {
		t.Fatalf("Validate(KindIE, ...) err = %v", err)
	}
	if !ok {
		t.Fatal("Validate(KindIE, valid sample) = false, want true")
	}
}

func FuzzIEValidate(f *testing.F) {
	e := NewIE()
	f.Add("110.042.490.114")
	f.Add("388108598269")
	f.Add("")
	f.Add("garbage-input")
	f.Fuzz(func(t *testing.T, s string) {
		// Must never panic; results are ignored.
		_ = e.Validate(s)
		_, _ = e.Format(s)
		_, _ = e.ValidateUF(s, UFSP)
	})
}

func BenchmarkIEValidate(b *testing.B) {
	e := NewIE()
	const sample = "110.042.490.114"
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = e.Validate(sample)
	}
}

func ExampleIE_Validate() {
	e := NewIE()
	fmt.Println(e.Validate("110.042.490.114"))
	// Output: true
}

// Compile-time interface conformance.
var (
	_ Document = (*IE)(nil)
	_ UFScoped = (*IE)(nil)
)
