package brdoc

import (
	"errors"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestVoterIDValidate(t *testing.T) {
	v := NewVoterID()

	tests := []struct {
		name  string
		input string
		want  bool
	}{
		// Valid samples generated by the algorithm: seq+uf → compute dv1,dv2
		// seq=10643870, uf=01 → dv1=0, dv2=8 → "106438700108"
		{name: "valid SP code 01", input: "106438700108", want: true},
		// seq=38990186, uf=28 → dv1=5, dv2=2 → "389901862852"
		{name: "valid exterior code 28", input: "389901862852", want: true},
		{name: "valid with spaces", input: "1064 3870 0108", want: true},
		{name: "wrong length short", input: "10643870011", want: false},
		{name: "wrong length long", input: "1064387001160", want: false},
		{name: "all equal", input: "222222222222", want: false},
		{name: "uf code 00 invalid", input: "100000000017", want: false},
		{name: "uf code 29 invalid", input: "100000002937", want: false},
		{name: "off-by-one last digit", input: "106438700109", want: false},
		{name: "off-by-one dv1", input: "106438700118", want: false},
		{name: "empty", input: "", want: false},
		{name: "non-digit", input: "1064387001AB", want: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, v.Validate(tt.input))
		})
	}
}

func TestVoterIDGenerate(t *testing.T) {
	v := NewVoterID()

	for i := 0; i < 1000; i++ {
		got := v.Generate()
		require.Len(t, got, VoterIDLength, "generated voter ID must be 12 digits")
		assert.True(t, v.Validate(got), "generated voter ID %q must validate", got)
	}
}

func TestVoterIDFormat(t *testing.T) {
	v := NewVoterID()

	tests := []struct {
		name    string
		input   string
		want    string
		wantErr error
	}{
		{name: "valid grouping", input: "106438700108", want: "1064 3870 0108"},
		{name: "already grouped", input: "1064 3870 0108", want: "1064 3870 0108"},
		{name: "too short", input: "10643870011", wantErr: ErrInvalidLength},
		{name: "too long", input: "1064387001160", wantErr: ErrInvalidLength},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := v.Format(tt.input)
			if tt.wantErr != nil {
				require.Error(t, err)
				assert.True(t, errors.Is(err, tt.wantErr), "want %v, got %v", tt.wantErr, err)
				return
			}

			require.NoError(t, err)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestVoterIDOrigin(t *testing.T) {
	v := NewVoterID()

	// Valid voter IDs built as seq+uf → compute dv1,dv2 so Origin receives a
	// well-formed 12-digit string for each UF code under test.
	tests := []struct {
		name    string
		input   string
		want    string
		wantErr error
	}{
		// Boundary: first valid code
		{name: "SP code 01", input: "106438700108", want: "São Paulo"},
		// Mid-range spot checks — one per ~5-code band to catch transposition typos
		{name: "BA code 05", input: "200000010523", want: "Bahia"},
		{name: "GO code 10", input: "876543211023", want: "Goiás"},
		{name: "PI code 15", input: "300000011546", want: "Piauí"},
		{name: "MS code 19", input: "400000011961", want: "Mato Grosso do Sul"},
		{name: "DF code 20", input: "500000012089", want: "Distrito Federal"},
		{name: "AM code 22", input: "111111122291", want: "Amazonas"},
		{name: "TO code 27", input: "600000012704", want: "Tocantins"},
		// Boundary: last valid code (exterior/abroad)
		{name: "exterior code 28", input: "389901862852", want: "Exterior"},
		// Error paths
		{name: "wrong length", input: "10643870", wantErr: ErrInvalidLength},
		{name: "invalid format", input: "999999990017", wantErr: ErrInvalidFormat},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := v.Origin(tt.input)
			if tt.wantErr != nil {
				require.Error(t, err)
				assert.True(t, errors.Is(err, tt.wantErr), "want %v, got %v", tt.wantErr, err)
				return
			}

			require.NoError(t, err)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestVoterIDImplementsOriginResolver(t *testing.T) {
	var _ OriginResolver = NewVoterID()
}

func BenchmarkVoterIDValidate(b *testing.B) {
	v := NewVoterID()
	const sample = "106438700108"

	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		_ = v.Validate(sample)
	}
}

func BenchmarkVoterIDGenerate(b *testing.B) {
	v := NewVoterID()

	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		_ = v.Generate()
	}
}
