// Code generated by selo gen --lang js. DO NOT EDIT.
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    include: ["test/**/*.test.js"],
  },
});
