<?php

// Code generated by selo gen --lang php. DO NOT EDIT.
//
// Shared mod-11 reducer used by the numeric / alphanumeric check-digit kinds
// (groups A, B, C). Parameterized by a spec array transcribed from the verified
// selo Go library so every language port applies the identical algorithm.

declare(strict_types=1);

namespace Selo;

final class Mod11
{
    /**
     * Map an alphanumeric CNPJ character to its numeric value.
     * '0'-'9' -> 0-9, 'A'-'Z' -> 17-42.
     */
    public static function charValue(string $ch): int
    {
        $c = ord($ch);
        if ($c >= 48 && $c <= 57) {
            return $c - 48;
        }
        if ($c >= 65 && $c <= 90) {
            return $c - 65 + 17;
        }
        return -1;
    }

    /**
     * Compute sum(values[i] * weights[i]).
     *
     * When cycleRightToLeft is true (CNPJ), the listed single cycle is applied
     * from the rightmost value, repeating.
     *
     * @param array<int, int> $values
     * @param array<int, int> $weights
     */
    public static function weightedSum(array $values, array $weights, bool $cycleRightToLeft = false): int
    {
        $total = 0;
        if ($cycleRightToLeft) {
            $j = 0;
            $n = count($weights);
            for ($i = count($values) - 1; $i >= 0; $i--) {
                $total += $values[$i] * $weights[$j];
                $j = ($j + 1) % $n;
            }
            return $total;
        }
        for ($i = 0; $i < count($weights); $i++) {
            $total += $values[$i] * $weights[$i];
        }
        return $total;
    }

    /**
     * Fold a weighted sum into a numeric check value per the rule.
     *
     * @param array{weights?: array<int,int>, rule: string, remainder_to0?: array<int,int>, multiply_by10?: bool, encode_x_at?: int, encode_zero_at?: int} $cd
     */
    public static function computeDigit(int $total, array $cd): int
    {
        $rule = $cd['rule'];
        if ($rule === 'eleven_minus') {
            return 11 - ($total % 11);
        }
        if ($rule === 'mod_remainder') {
            $multiply = !empty($cd['multiply_by10']);
            $rest = $multiply ? ($total * 10) % 11 : $total % 11;
            $r0 = $cd['remainder_to0'] ?? [];
            if (in_array($rest, $r0, true)) {
                return 0;
            }
            $rawRemainderFold = $multiply;
            foreach ($r0 as $r) {
                if ($r >= 10) {
                    $rawRemainderFold = true;
                }
            }
            return $rawRemainderFold ? $rest : 11 - $rest;
        }
        if ($rule === 'rightmost_digit') {
            return ($total % 11) % 10;
        }
        if ($rule === 'sum_zero') {
            return $total % 11; // valid when 0
        }
        return -1;
    }

    /**
     * Render a computed value as its check character.
     *
     * @param array{encode_x_at?: int, encode_zero_at?: int} $cd
     */
    public static function encodeDigit(int $value, array $cd): string
    {
        if (!empty($cd['encode_x_at']) && $value === $cd['encode_x_at']) {
            return 'X';
        }
        if (!empty($cd['encode_zero_at']) && $value === $cd['encode_zero_at']) {
            return '0';
        }
        return (string) $value;
    }

    /** Keep the ASCII digits of s. */
    public static function onlyDigits(string $s): string
    {
        $out = '';
        $len = strlen($s);
        for ($i = 0; $i < $len; $i++) {
            $ch = $s[$i];
            if ($ch >= '0' && $ch <= '9') {
                $out .= $ch;
            }
        }
        return $out;
    }

    /** Report whether every character of s is identical (s non-empty). */
    public static function allEqual(string $s): bool
    {
        if (strlen($s) === 0) {
            return false;
        }
        $first = $s[0];
        $len = strlen($s);
        for ($i = 1; $i < $len; $i++) {
            if ($s[$i] !== $first) {
                return false;
            }
        }
        return true;
    }
}
