// Code generated by selo gen --lang rust. DO NOT EDIT.
//
// Shared mod-11 reducer used by the numeric / alphanumeric check-digit kinds
// (groups A, B, C). Parameterized by a CheckDigit struct transcribed from the
// verified selo Go library so every language port applies the identical
// algorithm.

use std::cell::Cell;
use std::time::{SystemTime, UNIX_EPOCH};

/// How a weighted mod-11 sum is folded into a check digit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Rule {
    ElevenMinus,
    ModRemainder,
    RightmostDigit,
    SumZero,
}

/// Declarative description of one check digit (or, for SumZero, one verify pass),
/// transcribed from the selo Go library.
pub struct CheckDigit {
    pub weights: &'static [i32],
    pub rule: Rule,
    pub remainder_to0: &'static [i32],
    pub multiply_by10: bool,
    pub encode_x_at: i32,
    pub encode_zero_at: i32,
}

/// The two error sentinels the whole selo surface uses.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeloError {
    InvalidLength,
    InvalidFormat,
}

impl std::fmt::Display for SeloError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            SeloError::InvalidLength => "ErrInvalidLength",
            SeloError::InvalidFormat => "ErrInvalidFormat",
        };
        f.write_str(s)
    }
}

impl std::error::Error for SeloError {}

/// '0'-'9' -> 0-9, 'A'-'Z' -> 17-42, else -1.
pub fn char_value(ch: u8) -> i32 {
    if ch.is_ascii_digit() {
        (ch - b'0') as i32
    } else if ch.is_ascii_uppercase() {
        (ch - b'A') as i32 + 17
    } else {
        -1
    }
}

/// Compute sum(values[i] * weights[i]). When cycle_right_to_left is true (CNPJ),
/// the listed single cycle is applied from the rightmost value, repeating.
pub fn weighted_sum(values: &[i32], weights: &[i32], cycle_right_to_left: bool) -> i32 {
    let mut total = 0;
    if cycle_right_to_left {
        let mut j = 0;
        let n = weights.len();
        for i in (0..values.len()).rev() {
            total += values[i] * weights[j];
            j = (j + 1) % n;
        }
        return total;
    }
    for i in 0..weights.len() {
        total += values[i] * weights[i];
    }
    total
}

/// Fold a weighted sum into a numeric check value per the rule.
pub fn compute_digit(total: i32, cd: &CheckDigit) -> i32 {
    match cd.rule {
        Rule::ElevenMinus => 11 - (total % 11),
        Rule::ModRemainder => {
            let rest = if cd.multiply_by10 {
                (total * 10) % 11
            } else {
                total % 11
            };
            if cd.remainder_to0.contains(&rest) {
                return 0;
            }
            // CRITICAL: CPF/RENAVAM/VoterID-DV (multiply_by10 OR a
            // remainder_to0 >= 10) return `rest`; CNPJ/PIS (remainder_to0 =
            // {0,1}) return 11 - rest.
            let raw_remainder_fold =
                cd.multiply_by10 || cd.remainder_to0.iter().any(|&r| r >= 10);
            if raw_remainder_fold {
                rest
            } else {
                11 - rest
            }
        }
        Rule::RightmostDigit => (total % 11) % 10,
        Rule::SumZero => total % 11, // valid when 0
    }
}

/// Render a computed value as its check character.
pub fn encode_digit(value: i32, cd: &CheckDigit) -> String {
    if cd.encode_x_at != 0 && value == cd.encode_x_at {
        return "X".into();
    }
    if cd.encode_zero_at != 0 && value == cd.encode_zero_at {
        return "0".into();
    }
    value.to_string()
}

/// Keep the ASCII digits of s.
pub fn only_digits(s: &str) -> String {
    s.bytes()
        .filter(|b| b.is_ascii_digit())
        .map(|b| b as char)
        .collect()
}

/// Report whether every character of s is identical (s non-empty).
pub fn all_equal(s: &str) -> bool {
    let b = s.as_bytes();
    if b.is_empty() {
        return false;
    }
    b.iter().all(|&c| c == b[0])
}

// --- In-crate PRNG (no `rand` dependency) ----------------------------------
//
// PHP uses random_int; Python uses random. To keep the generated crate
// zero-runtime-dependency, the generate_* helpers use this tiny private
// xorshift64* PRNG. The round-trip self-tests only need validity, not
// cryptographic quality.

thread_local! {
    static RNG_STATE: Cell<u64> = Cell::new(seed());
}

fn seed() -> u64 {
    let n = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos() as u64;
    n ^ 0x9E3779B97F4A7C15
}

/// xorshift64*; uniform enough for generate_* round-trip self-tests.
pub fn rand_u64() -> u64 {
    RNG_STATE.with(|s| {
        let mut x = s.get();
        if x == 0 {
            x = 0x9E3779B97F4A7C15;
        }
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        s.set(x);
        x.wrapping_mul(0x2545F4914F6CDD1D)
    })
}

/// Uniform in 0..=max.
pub fn rand_int(max: u64) -> u64 {
    rand_u64() % (max + 1)
}
