// Code generated by selo gen --lang ts. DO NOT EDIT.
//
// Shared mod-11 reducer used by the numeric / alphanumeric check-digit kinds
// (groups A, B, C). It is parameterized by a CheckDigit spec transcribed from
// the verified selo Go library, so every language port applies the identical
// algorithm.

/** DV reduction rule (mirrors codegen.DVRule). */
export type DVRule =
  | "eleven_minus"
  | "mod_remainder"
  | "rightmost_digit"
  | "sum_zero";

/** One check-digit (or, for sum_zero, one verify pass) specification. */
export interface CheckDigit {
  /** Positional mod-11 weights, in input (left-to-right) order. */
  weights: number[];
  /** How the weighted sum becomes the check digit / verification result. */
  rule: DVRule;
  /** Remainder values (of the rule's fold) that collapse to a 0 check digit. */
  remainderTo0?: number[];
  /** When true the fold is (sum*10)%11 rather than sum%11 (mod_remainder only). */
  multiplyBy10?: boolean;
  /** Computed value that encodes as the character 'X' (RG: 10). 0 = none. */
  encodeXAt?: number;
  /** Computed value that encodes as the character '0' (RG: 11). 0 = none. */
  encodeZeroAt?: number;
}

/** Alphanumeric CNPJ char -> value map ('0'-'9' -> 0-9, 'A'-'Z' -> 17-42). */
export function charValue(ch: string): number {
  const c = ch.charCodeAt(0);
  if (c >= 48 && c <= 57) return c - 48; // '0'-'9'
  if (c >= 65 && c <= 90) return c - 65 + 17; // 'A'-'Z'
  return -1;
}

/**
 * weightedSum computes Sum(value[i] * weights[i]). For cycling weights
 * (CNPJ) pass cycleRightToLeft=true: the listed single cycle (2..9) is
 * applied from the rightmost base character, repeating.
 */
export function weightedSum(
  values: number[],
  weights: number[],
  cycleRightToLeft = false,
): number {
  let sum = 0;
  if (cycleRightToLeft) {
    let j = 0;
    for (let i = values.length - 1; i >= 0; i--) {
      sum += values[i] * weights[j];
      j = (j + 1) % weights.length;
    }
    return sum;
  }
  for (let i = 0; i < weights.length; i++) {
    sum += values[i] * weights[i];
  }
  return sum;
}

/**
 * computeDigit folds a weighted sum into a numeric check value per the rule.
 * Returns a number 0..11 (10/11 may be encoded as characters by the caller).
 */
export function computeDigit(sum: number, cd: CheckDigit): number {
  switch (cd.rule) {
    case "eleven_minus": {
      return 11 - (sum % 11);
    }
    case "mod_remainder": {
      const rest = cd.multiplyBy10 ? (sum * 10) % 11 : sum % 11;
      if (cd.remainderTo0 && cd.remainderTo0.includes(rest)) {
        return 0;
      }
      // Two folds share this rule: the "raw remainder" family (CPF/RENAVAM via
      // *10, and voter_id) maps a high remainder (10/11) to 0 and returns the
      // remainder itself; the "eleven-minus" family (PIS/CNPJ) maps a low
      // remainder (0/1) to 0 and returns 11-remainder. The remainderTo0 set
      // disambiguates: a set containing >=10 selects the raw-remainder fold.
      const rawRemainderFold =
        cd.multiplyBy10 ||
        (cd.remainderTo0 !== undefined && cd.remainderTo0.some((r) => r >= 10));
      return rawRemainderFold ? rest : 11 - rest;
    }
    case "rightmost_digit": {
      return (sum % 11) % 10;
    }
    case "sum_zero": {
      return sum % 11; // valid when 0
    }
    default:
      return -1;
  }
}

/** encodeDigit renders a computed value as its check character. */
export function encodeDigit(value: number, cd: CheckDigit): string {
  if (cd.encodeXAt && value === cd.encodeXAt) return "X";
  if (cd.encodeZeroAt && value === cd.encodeZeroAt) return "0";
  return String(value);
}

/** onlyDigits keeps the ASCII digits of s. */
export function onlyDigits(s: string): string {
  let out = "";
  for (const ch of s) {
    if (ch >= "0" && ch <= "9") out += ch;
  }
  return out;
}

/** allEqual reports whether every character of s is identical (s non-empty). */
export function allEqual(s: string): boolean {
  if (s.length === 0) return false;
  for (let i = 1; i < s.length; i++) {
    if (s[i] !== s[0]) return false;
  }
  return true;
}
